// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVMaMtACft2n11LDFJuy6vtiaNh6lM4eM',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: '218564066910',
    projectId: 'eurohabesha-f3929',
    authDomain: 'eurohabesha-f3929.firebaseapp.com',
    storageBucket: 'eurohabesha-f3929.firebasestorage.app',
    measurementId: 'YOUR_MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVMaMtACft2n11LDFJuy6vtiaNh6lM4eM',
    appId: '1:218564066910:android:e7900e60c10457a50f7ecf',
    messagingSenderId: '218564066910',
    projectId: 'eurohabesha-f3929',
    storageBucket: 'eurohabesha-f3929.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVMaMtACft2n11LDFJuy6vtiaNh6lM4eM',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '218564066910',
    projectId: 'eurohabesha-f3929',
    storageBucket: 'eurohabesha-f3929.firebasestorage.app',
    iosBundleId: 'com.example.euroHabesha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVMaMtACft2n11LDFJuy6vtiaNh6lM4eM',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: '218564066910',
    projectId: 'eurohabesha-f3929',
    storageBucket: 'eurohabesha-f3929.firebasestorage.app',
    iosBundleId: 'com.example.euroHabesha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVMaMtACft2n11LDFJuy6vtiaNh6lM4eM',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: '218564066910',
    projectId: 'eurohabesha-f3929',
    storageBucket: 'eurohabesha-f3929.firebasestorage.app',
  );
}
